"""Document status constants."""


DOCUMENT_STATUS_UPLOADED = "uploaded"
DOCUMENT_STATUS_PROCESSING = "processing"
DOCUMENT_STATUS_READY = "ready"
DOCUMENT_STATUS_FAILED = "failed"
DOCUMENT_STATUSES = [
    DOCUMENT_STATUS_UPLOADED,
    DOCUMENT_STATUS_PROCESSING,
    DOCUMENT_STATUS_READY,
    DOCUMENT_STATUS_FAILED,
]

DEFAULT_UPLOAD_FILE_NAME = "uploaded-document.txt"
DEFAULT_UPLOAD_CONTENT_TYPE = "text/plain"

DEFAULT_CHUNK_MAX_CHARACTERS = 1200
DEFAULT_CHUNK_OVERLAP_CHARACTERS = 150
