"""Permission values used by document access checks."""


DOCUMENT_PERMISSION_READ = "read"
DOCUMENT_PERMISSION_WRITE = "write"
DOCUMENT_PERMISSION_OWNER = "owner"

DOCUMENT_READ_PERMISSIONS = [
    DOCUMENT_PERMISSION_READ,
    DOCUMENT_PERMISSION_WRITE,
    DOCUMENT_PERMISSION_OWNER,
]
DOCUMENT_WRITE_PERMISSIONS = [
    DOCUMENT_PERMISSION_WRITE,
    DOCUMENT_PERMISSION_OWNER,
]
DOCUMENT_DELETE_PERMISSIONS = [DOCUMENT_PERMISSION_OWNER]
